spring:
  h2:
    console:
      enabled: true

  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: test-bucket

jwt:
  secret:
    key: bXlTdXBlclNlY3JldEtleUZvckpXVFRlc3RpbmdBbmRTcHJpbmdCb290M1NlY3VyaXR5

google:
  user: test@gmail.com
  password: 1q2w3e4r!!