spring:

  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://mysql:3306/vote_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vote
    password: votepassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

jwt:
  secret:
    key: bXlTdXBlclNlY3JldEtleUZvckpXVFRlc3RpbmdBbmRTcHJpbmdCb290M1NlY3VyaXR5