spring:

  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/vote_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vote
    password: votepassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: test-bucket

jwt:
  secret:
    key: bXlTdXBlclNlY3JldEtleUZvckpXVFRlc3RpbmdBbmRTcHJpbmdCb290M1NlY3VyaXR5

google:
  user: test@gmail.com
  password: 1q2w3e4r!!